0:
  agent_type: dqn
  env_type: gym
  game: LunarLander-v2
  model_type: dqn_mlp
  memory_type: replaybuffer
  actions_legend: ["Nop", "left engine", "main engine", "right engine"]

1:
  agent_type: dqn
  env_type: unity
  game: envs/Banana_Linux_NoVis/Banana.x86_64
  model_type: dqn_mlp
  memory_type: replaybuffer
  actions_legend: ["walk forward", "walk backward", "turn left", "turn right"]
